### ISSUE TITLE
Fan flow card on or off does not work

### ISSUE THREAD

**Issue by salbang** [AdyRock/com.switchbot#10]
On/Off button works by itself, but it does nothing in a flow.

Aircom flow does not work either. It might be a wider spread problem over all flow processing.

**Comment by AdyRock** [comment]
Fixed in new test update.
Thanks for letting me know.

**Comment by AdyRock** [comment]
Fixed in new test update.
Thanks for letting me know.

**Comment by salbang** [comment]
Aircon off flow card still does not work. Aircon on card works.

**Comment by AdyRock** [comment]
Doh, thanks for catching that.
In version 0.3.17 I optimised the code to make it smaller and more efficient but I missed that one.
Version 0.3.20 is now in test.

**Comment by salbang** [comment]
I've been testing the new versioN for several days. I am OK with it so far.

**Comment by salbang** [comment]
Left a reply in the forum. Thermostats don't refresh as often as before. Could you please check? ![image](https://user-images.githubusercontent.com/12740762/134767312-60b80d82-633c-4a53-a91f-a08434a535ae.png)

**Comment by AdyRock** [comment]
I think this was resolved in the forum so I will close the issue but please get back to me if you have any more problems.
