### ISSUE TITLE
Unable to connect Switchbot account with Homey

### ISSUE THREAD

**Issue by laganbo** [AdyRock/com.switchbot#128]
![switchbot](https://github.com/user-attachments/assets/adb07472-6cc3-4ffa-808c-22cb96e1d57e)
When I try to connect my Switchbot account with Homey, I receive the error message above.
I have previously contacted both Switchbot and Homey support regarding this issue without receiving any assistance.
Please help resolve this!

**Comment by AdyRock** [comment]
There is a known issue if you are logging in with a Google account. 
If you are using an email account, then it could just be a temporary issue on the servers.

**Comment by marcelmarty** [comment]
Same problem here, since more than 5 days... Seems not to be a temporary problem.

**Comment by AdyRock** [comment]
Are you using email to login or a Google account?

**Comment by marcelmarty** [comment]
@AdyRock I'm using a Google-Account.

**Comment by AdyRock** [comment]
There is a known issue with the the Google login. The only solution at the moment is to change to an email login, which involves creating a new account and asking SwitchBot to migrate your devices.

I have been in contact with SwitchBot about this a number of times but it seems to be falling on deaf ears.

**Comment by AdyRock** [comment]
I have published a new test version that has an updated login system using the new servers.
Could you give that a try to see if it works for you?

**Comment by laganbo** [comment]
Hello,
I just tested but I still have the same issue.

BR
Roy

Den ons 25 sep. 2024 kl 11:35 skrev Adrian Rockall ***@***.***

**Comment by AdyRock** [comment]
Did you update to the new test version?

**Comment by marcelmarty** [comment]
@laganbo You need to install the version which can be found at https://homey.app/de-ch/app/com.switchbot/SwitchBot/test

**Comment by laganbo** [comment]
Sorry,
I didn´t realize tha I should install the new app but now when I installed
it I could authorize Switchbot (webapp)!
In the next step I get "Invalid response code:190"


[image: image.png]

**Comment by AdyRock** [comment]
No image is appearing.

What device where you trying to add?

**Comment by laganbo** [comment]
I´m trying to add Switchbot lock (HUB).
I tested again with same result:

[image: SB.jpg]

Den ons 25 sep. 2024 kl 14:34 skrev Adrian Rockall ***@***.***

**Comment by AdyRock** [comment]
I have seen that issue with the lock before. Can you try enabling the develop moe in the SwitchBot app to see if that fixes it?

Open the SwitchBot phone app, go to profile - Preferences - About and then tap on the App Version hundreds of times until you see a new item called Developer appear. Then try to add the lock again.

**Comment by laganbo** [comment]
Hello,
I activated Developer and tried again and now it worked! All three locks
are now visible in Homey! :)
I´ll test more this evening when I´m home from work.

br
Roy

Den ons 25 sep. 2024 kl 17:33 skrev Adrian Rockall ***@***.***
